### ISSUE TITLE
Hallo.

### ISSUE THREAD

**Issue by mirekklita** [Jellepepe/radiodb#73]
Hallo.
Please add Polish radio stations:

-Radio Party
https://radioparty.pl/kanalglowny

-Radio Fest 
http://radiofest.pl/tplayerfull/fullplayer.html

-Muzyczne Radio
https://muzyczneradio.pl/index.php/player/192.html

-Radio Top 80s
http://top80s.pl//

-RMF Classic
https://myradioonline.pl/rmf-classic

Thank You

_Originally posted by @mirekklita in https://github.com/Jellepepe/radiodb/issues/47#issuecomment-1252775014_

**Comment by mirekklita** [comment]
Please, add the radio stations that I am asking for.

**Comment by Jellepepe** [comment]
Hey, It took a while as I never saw this, but I added these stations to the new database (https://radio.byme.dev), they should be visible in the app.
